version: '3'
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=fourlanches
      - POSTGRES_HOST_AUTH_METHOD="trust"
    ports:
      - "5432:5432"
  app:
    image: fourlanches
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fourlanches
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"
  migration:
    container_name: migration
    image: flyway/flyway
    environment:
      - FLYWAY_USER=${DATABASE_USERNAME}
      - FLYWAY_PASSWORD=${DATABASE_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db:5432/fourlanches
      - FLYWAY_SCHEMAS=public
      - FLYWAY_GROUP=true
#    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      # - ./src/main/resources/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - db