version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: fourlanches
    ports:
      - "5432:5432"
    volumes:
      - db:./postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fourlanches
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=p@ssw0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db:
    driver: local